version: "3"

tasks:
  init:
    desc: Initialize Backend
    cmds:
      - pip install pipenv
      - pipenv install --dev
      - pipenv shell

  shell:
    desc: Start Python Virtual Environment
    cmds:
  
  mac-init:
    desc: Initialize Backend with Mac
    cmds:
      - pip3 install pipenv
      - pipenv install --dev
      - pipenv shell
