# Generated by Django 5.0.4 on 2024-04-16 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_dietarypreferences_user_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dietarypreferences",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="favoriterecipes",
            old_name="preference_id",
            new_name="preference",
        ),
        migrations.RenameField(
            model_name="favoriterecipes",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="ingredients",
            old_name="preference_id",
            new_name="preference",
        ),
        migrations.RenameField(
            model_name="ingredients",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="macros",
            old_name="ingredient_id",
            new_name="ingredient",
        ),
        migrations.RenameField(
            model_name="macros",
            old_name="recipe_id",
            new_name="recipe",
        ),
        migrations.RenameField(
            model_name="macros",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="shoppinglist",
            old_name="ingredient_id",
            new_name="ingredient",
        ),
        migrations.RenameField(
            model_name="shoppinglist",
            old_name="user_id",
            new_name="user",
        ),
    ]
