# Generated by Django 5.0.4 on 2024-04-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_dietarypreferences_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoriterecipes",
            name="image",
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name="favoriterecipes",
            name="likes",
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name="favoriterecipes",
            name="minutes",
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name="favoriterecipes",
            name="name",
            field=models.CharField(default=False, max_length=100),
        ),
    ]
