# Generated by Django 5.0.4 on 2024-04-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_macro_type_macro_macro_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietarypreference",
            name="preference_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
