# Generated by Django 5.0.4 on 2024-04-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_dietarypreferences_dietarypreference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoriterecipe",
            name="image",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="favoriterecipe",
            name="likes",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="favoriterecipe",
            name="minutes",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="favoriterecipe",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
