# Generated by Django 5.0.4 on 2024-04-21 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_dietarypreference_preference_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favoriterecipe",
            name="preference",
        ),
    ]
