# Generated by Django 5.0.4 on 2024-04-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_favoriterecipe_preference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="macro",
            name="macro_name",
        ),
        migrations.RemoveField(
            model_name="macro",
            name="quantity",
        ),
        migrations.AddField(
            model_name="macro",
            name="date",
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="macro",
            name="macro_names",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="macro",
            name="quantities",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="macro",
            name="recipe_id",
            field=models.CharField(max_length=100),
        ),
    ]
