# Generated by Django 5.0.4 on 2024-04-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_plannedrecipe_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="image",
            field=models.CharField(
                default="https://placeholder.pics/svg/300/DEDEDE/555555/image",
                max_length=255,
            ),
        ),
    ]
