# Generated by Django 5.0.4 on 2024-04-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_macro_macro_name_remove_macro_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shoppinglist",
            name="quantity",
        ),
        migrations.AddField(
            model_name="shoppinglist",
            name="recipe_id",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
