export const mock = {
  vegetarian: false,
  vegan: false,
  glutenFree: true,
  dairyFree: true,
  veryHealthy: false,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  lowFodmap: false,
  weightWatcherSmartPoints: 15,
  gaps: 'no',
  preparationMinutes: -1,
  cookingMinutes: -1,
  aggregateLikes: 19,
  healthScore: 18,
  creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
  license: 'CC BY 3.0',
  sourceName: 'Foodista',
  pricePerServing: 306.86,
  extendedIngredients: [
    {
      id: 13023,
      aisle: 'Meat',
      image: 'beef-brisket.png',
      consistency: 'SOLID',
      name: 'brisket',
      nameClean: 'beef brisket',
      original: '1 brisket, 5 lbs., first cut',
      originalName: 'brisket, 5 lbs., first cut',
      amount: 1,
      unit: '',
      meta: [],
      measures: {
        us: {
          amount: 1,
          unitShort: '',
          unitLong: '',
        },
        metric: {
          amount: 1,
          unitShort: '',
          unitLong: '',
        },
      },
    },
    {
      id: 1102047,
      aisle: 'Spices and Seasonings',
      image: 'salt-and-pepper.jpg',
      consistency: 'SOLID',
      name: 'salt and pepper',
      nameClean: 'salt and pepper',
      original: 'Salt and pepper',
      originalName: 'Salt and pepper',
      amount: 8,
      unit: 'servings',
      meta: [],
      measures: {
        us: {
          amount: 8,
          unitShort: 'servings',
          unitLong: 'servings',
        },
        metric: {
          amount: 8,
          unitShort: 'servings',
          unitLong: 'servings',
        },
      },
    },
    {
      id: 4582,
      aisle: 'Oil, Vinegar, Salad Dressing',
      image: 'vegetable-oil.jpg',
      consistency: 'LIQUID',
      name: 'oil',
      nameClean: 'cooking oil',
      original: '2 Tbs. oil for searing',
      originalName: 'oil for searing',
      amount: 2,
      unit: 'Tbs',
      meta: ['for searing'],
      measures: {
        us: {
          amount: 2,
          unitShort: 'Tbs',
          unitLong: 'Tbs',
        },
        metric: {
          amount: 2,
          unitShort: 'Tbs',
          unitLong: 'Tbs',
        },
      },
    },
    {
      id: 2026,
      aisle: 'Spices and Seasonings',
      image: 'onion-powder.jpg',
      consistency: 'SOLID',
      name: 'onion powder',
      nameClean: 'onion powder',
      original: '1 tsp onion powder',
      originalName: 'onion powder',
      amount: 1,
      unit: 'tsp',
      meta: [],
      measures: {
        us: {
          amount: 1,
          unitShort: 'tsp',
          unitLong: 'teaspoon',
        },
        metric: {
          amount: 1,
          unitShort: 'tsp',
          unitLong: 'teaspoon',
        },
      },
    },
    {
      id: 1022020,
      aisle: 'Spices and Seasonings',
      image: 'garlic-powder.png',
      consistency: 'SOLID',
      name: 'garlic powder',
      nameClean: 'garlic powder',
      original: '1/2 tsp garlic powder',
      originalName: 'garlic powder',
      amount: 0.5,
      unit: 'tsp',
      meta: [],
      measures: {
        us: {
          amount: 0.5,
          unitShort: 'tsps',
          unitLong: 'teaspoons',
        },
        metric: {
          amount: 0.5,
          unitShort: 'tsps',
          unitLong: 'teaspoons',
        },
      },
    },
    {
      id: 1012028,
      aisle: 'Spices and Seasonings',
      image: 'paprika.jpg',
      consistency: 'SOLID',
      name: 'paprika',
      nameClean: 'smoked paprika',
      original: '1/2 tsp smoked paprika (optional)',
      originalName: 'smoked paprika (optional)',
      amount: 0.5,
      unit: 'tsp',
      meta: ['smoked'],
      measures: {
        us: {
          amount: 0.5,
          unitShort: 'tsps',
          unitLong: 'teaspoons',
        },
        metric: {
          amount: 0.5,
          unitShort: 'tsps',
          unitLong: 'teaspoons',
        },
      },
    },
    {
      id: 1002014,
      aisle: 'Spices and Seasonings',
      image: 'ground-cumin.jpg',
      consistency: 'SOLID',
      name: 'cumin',
      nameClean: 'cumin',
      original: '1/2 tsp cumin',
      originalName: 'cumin',
      amount: 0.5,
      unit: 'tsp',
      meta: [],
      measures: {
        us: {
          amount: 0.5,
          unitShort: 'tsps',
          unitLong: 'teaspoons',
        },
        metric: {
          amount: 0.5,
          unitShort: 'tsps',
          unitLong: 'teaspoons',
        },
      },
    },
    {
      id: 2031,
      aisle: 'Spices and Seasonings',
      image: 'chili-powder.jpg',
      consistency: 'SOLID',
      name: 'cayenne pepper',
      nameClean: 'ground cayenne pepper',
      original: '1/4 tsp cayenne pepper (use 1/2 tsp for more heat)',
      originalName: 'cayenne pepper (use 1/2 tsp for more heat)',
      amount: 0.25,
      unit: 'tsp',
      meta: ['(use)'],
      measures: {
        us: {
          amount: 0.25,
          unitShort: 'tsps',
          unitLong: 'teaspoons',
        },
        metric: {
          amount: 0.25,
          unitShort: 'tsps',
          unitLong: 'teaspoons',
        },
      },
    },
    {
      id: 6150,
      aisle: 'Condiments',
      image: 'barbecue-sauce.jpg',
      consistency: 'SOLID',
      name: 'smokey barbecue sauce',
      nameClean: 'barbecue sauce',
      original: '1 1/2 cups smokey barbecue sauce',
      originalName: 'smokey barbecue sauce',
      amount: 1.5,
      unit: 'cups',
      meta: [],
      measures: {
        us: {
          amount: 1.5,
          unitShort: 'cups',
          unitLong: 'cups',
        },
        metric: {
          amount: 429,
          unitShort: 'ml',
          unitLong: 'milliliters',
        },
      },
    },
    {
      id: 19334,
      aisle: 'Baking',
      image: 'light-brown-sugar.jpg',
      consistency: 'SOLID',
      name: 'brown sugar',
      nameClean: 'golden brown sugar',
      original: '1/3 cup brown sugar',
      originalName: 'brown sugar',
      amount: 0.33333334,
      unit: 'cup',
      meta: [],
      measures: {
        us: {
          amount: 0.33333334,
          unitShort: 'cups',
          unitLong: 'cups',
        },
        metric: {
          amount: 73.333,
          unitShort: 'g',
          unitLong: 'grams',
        },
      },
    },
    {
      id: 19334,
      aisle: 'Baking',
      image: 'dark-brown-sugar.png',
      consistency: 'SOLID',
      name: 'brown sugar',
      nameClean: 'golden brown sugar',
      original: '1/3 cup brown sugar',
      originalName: 'brown sugar',
      amount: 0.33333334,
      unit: 'cup',
      meta: [],
      measures: {
        us: {
          amount: 0.33333334,
          unitShort: 'cups',
          unitLong: 'cups',
        },
        metric: {
          amount: 73.333,
          unitShort: 'g',
          unitLong: 'grams',
        },
      },
    },
    {
      id: 20027,
      aisle: 'Baking',
      image: 'white-powder.jpg',
      consistency: 'SOLID',
      name: 'cornstarch',
      nameClean: 'corn starch',
      original: '1/2 tbsp cornstarch',
      originalName: 'cornstarch',
      amount: 0.5,
      unit: 'tbsp',
      meta: [],
      measures: {
        us: {
          amount: 0.5,
          unitShort: 'Tbsps',
          unitLong: 'Tbsps',
        },
        metric: {
          amount: 0.5,
          unitShort: 'Tbsps',
          unitLong: 'Tbsps',
        },
      },
    },
  ],
  id: 634486,
  title: 'BBQ Beef Brisket',
  readyInMinutes: 45,
  servings: 8,
  sourceUrl: 'https://www.foodista.com/recipe/T3NNZRNQ/bbq-beef-brisket',
  image: 'https://img.spoonacular.com/recipes/634486-556x370.jpg',
  imageType: 'jpg',
  nutrition: {
    nutrients: [
      {
        name: 'Calories',
        amount: 548.87,
        unit: 'kcal',
        percentOfDailyNeeds: 27.44,
      },
      {
        name: 'Fat',
        amount: 20.61,
        unit: 'g',
        percentOfDailyNeeds: 31.7,
      },
      {
        name: 'Saturated Fat',
        amount: 6.16,
        unit: 'g',
        percentOfDailyNeeds: 38.51,
      },
      {
        name: 'Carbohydrates',
        amount: 40.85,
        unit: 'g',
        percentOfDailyNeeds: 13.62,
      },
      {
        name: 'Net Carbohydrates',
        amount: 40.23,
        unit: 'g',
        percentOfDailyNeeds: 14.63,
      },
      {
        name: 'Sugar',
        amount: 35.63,
        unit: 'g',
        percentOfDailyNeeds: 39.59,
      },
      {
        name: 'Cholesterol',
        amount: 140.59,
        unit: 'mg',
        percentOfDailyNeeds: 46.86,
      },
      {
        name: 'Sodium',
        amount: 931.09,
        unit: 'mg',
        percentOfDailyNeeds: 40.48,
      },
      {
        name: 'Protein',
        amount: 47.56,
        unit: 'g',
        percentOfDailyNeeds: 95.11,
      },
      {
        name: 'Vitamin B12',
        amount: 5.51,
        unit: 'µg',
        percentOfDailyNeeds: 91.83,
      },
      {
        name: 'Zinc',
        amount: 9.9,
        unit: 'mg',
        percentOfDailyNeeds: 66.01,
      },
      {
        name: 'Selenium',
        amount: 38.23,
        unit: 'µg',
        percentOfDailyNeeds: 54.61,
      },
      {
        name: 'Vitamin B6',
        amount: 1.01,
        unit: 'mg',
        percentOfDailyNeeds: 50.5,
      },
      {
        name: 'Phosphorus',
        amount: 470.24,
        unit: 'mg',
        percentOfDailyNeeds: 47.02,
      },
      {
        name: 'Vitamin B3',
        amount: 9.3,
        unit: 'mg',
        percentOfDailyNeeds: 46.5,
      },
      {
        name: 'Iron',
        amount: 4.97,
        unit: 'mg',
        percentOfDailyNeeds: 27.6,
      },
      {
        name: 'Potassium',
        amount: 908.61,
        unit: 'mg',
        percentOfDailyNeeds: 25.96,
      },
      {
        name: 'Vitamin B2',
        amount: 0.42,
        unit: 'mg',
        percentOfDailyNeeds: 24.62,
      },
      {
        name: 'Vitamin B1',
        amount: 0.24,
        unit: 'mg',
        percentOfDailyNeeds: 16.18,
      },
      {
        name: 'Magnesium',
        amount: 62.05,
        unit: 'mg',
        percentOfDailyNeeds: 15.51,
      },
      {
        name: 'Vitamin E',
        amount: 1.83,
        unit: 'mg',
        percentOfDailyNeeds: 12.18,
      },
      {
        name: 'Copper',
        amount: 0.23,
        unit: 'mg',
        percentOfDailyNeeds: 11.7,
      },
      {
        name: 'Vitamin B5',
        amount: 0.91,
        unit: 'mg',
        percentOfDailyNeeds: 9.13,
      },
      {
        name: 'Vitamin K',
        amount: 6.57,
        unit: 'µg',
        percentOfDailyNeeds: 6.26,
      },
      {
        name: 'Manganese',
        amount: 0.12,
        unit: 'mg',
        percentOfDailyNeeds: 6.24,
      },
      {
        name: 'Calcium',
        amount: 47.22,
        unit: 'mg',
        percentOfDailyNeeds: 4.72,
      },
      {
        name: 'Folate',
        amount: 17.54,
        unit: 'µg',
        percentOfDailyNeeds: 4.39,
      },
      {
        name: 'Vitamin A',
        amount: 206.68,
        unit: 'IU',
        percentOfDailyNeeds: 4.13,
      },
      {
        name: 'Fiber',
        amount: 0.62,
        unit: 'g',
        percentOfDailyNeeds: 2.49,
      },
    ],
    properties: [
      {
        name: 'Glycemic Index',
        amount: 7.13,
        unit: '',
      },
      {
        name: 'Glycemic Load',
        amount: 0.02,
        unit: '',
      },
      {
        name: 'Inflammation Score',
        amount: -3,
        unit: '',
      },
      {
        name: 'Nutrition Score',
        amount: 22.961739130434786,
        unit: '%',
      },
    ],
    flavonoids: [
      {
        name: 'Cyanidin',
        amount: 0,
        unit: '',
      },
      {
        name: 'Petunidin',
        amount: 0,
        unit: '',
      },
      {
        name: 'Delphinidin',
        amount: 0,
        unit: '',
      },
      {
        name: 'Malvidin',
        amount: 0,
        unit: '',
      },
      {
        name: 'Pelargonidin',
        amount: 0,
        unit: '',
      },
      {
        name: 'Peonidin',
        amount: 0,
        unit: '',
      },
      {
        name: 'Catechin',
        amount: 0,
        unit: '',
      },
      {
        name: 'Epigallocatechin',
        amount: 0,
        unit: '',
      },
      {
        name: 'Epicatechin',
        amount: 0,
        unit: '',
      },
      {
        name: 'Epicatechin 3-gallate',
        amount: 0,
        unit: '',
      },
      {
        name: 'Epigallocatechin 3-gallate',
        amount: 0,
        unit: '',
      },
      {
        name: 'Theaflavin',
        amount: 0,
        unit: '',
      },
      {
        name: 'Thearubigins',
        amount: 0,
        unit: '',
      },
      {
        name: 'Eriodictyol',
        amount: 0,
        unit: '',
      },
      {
        name: 'Hesperetin',
        amount: 0,
        unit: '',
      },
      {
        name: 'Naringenin',
        amount: 0,
        unit: '',
      },
      {
        name: 'Apigenin',
        amount: 0,
        unit: '',
      },
      {
        name: 'Luteolin',
        amount: 0,
        unit: '',
      },
      {
        name: 'Isorhamnetin',
        amount: 0,
        unit: '',
      },
      {
        name: 'Kaempferol',
        amount: 0,
        unit: '',
      },
      {
        name: 'Myricetin',
        amount: 0,
        unit: '',
      },
      {
        name: 'Quercetin',
        amount: 0,
        unit: '',
      },
      {
        name: "Theaflavin-3,3'-digallate",
        amount: 0,
        unit: '',
      },
      {
        name: "Theaflavin-3'-gallate",
        amount: 0,
        unit: '',
      },
      {
        name: 'Theaflavin-3-gallate',
        amount: 0,
        unit: '',
      },
      {
        name: 'Gallocatechin',
        amount: 0,
        unit: '',
      },
    ],
    ingredients: [
      {
        id: 13023,
        name: 'brisket',
        amount: 0.13,
        unit: '',
        nutrients: [
          {
            name: 'Copper',
            amount: 0.18,
            unit: 'mg',
            percentOfDailyNeeds: 11.7,
          },
          {
            name: 'Vitamin A',
            amount: 0,
            unit: 'IU',
            percentOfDailyNeeds: 4.13,
          },
          {
            name: 'Poly Unsaturated Fat',
            amount: 0.52,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Folate',
            amount: 15.87,
            unit: 'µg',
            percentOfDailyNeeds: 4.39,
          },
          {
            name: 'Folic Acid',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Cholesterol',
            amount: 140.59,
            unit: 'mg',
            percentOfDailyNeeds: 46.86,
          },
          {
            name: 'Selenium',
            amount: 37.19,
            unit: 'µg',
            percentOfDailyNeeds: 54.61,
          },
          {
            name: 'Choline',
            amount: 196.14,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Carbohydrates',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 13.62,
          },
          {
            name: 'Mono Unsaturated Fat',
            amount: 7.85,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Potassium',
            amount: 748.28,
            unit: 'mg',
            percentOfDailyNeeds: 25.96,
          },
          {
            name: 'Calcium',
            amount: 11.34,
            unit: 'mg',
            percentOfDailyNeeds: 4.72,
          },
          {
            name: 'Net Carbohydrates',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 14.63,
          },
          {
            name: 'Fat',
            amount: 16.71,
            unit: 'g',
            percentOfDailyNeeds: 31.7,
          },
          {
            name: 'Vitamin B6',
            amount: 0.95,
            unit: 'mg',
            percentOfDailyNeeds: 50.5,
          },
          {
            name: 'Vitamin B5',
            amount: 0.79,
            unit: 'mg',
            percentOfDailyNeeds: 9.13,
          },
          {
            name: 'Zinc',
            amount: 9.77,
            unit: 'mg',
            percentOfDailyNeeds: 66.01,
          },
          {
            name: 'Lycopene',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Fiber',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 2.49,
          },
          {
            name: 'Phosphorus',
            amount: 455.77,
            unit: 'mg',
            percentOfDailyNeeds: 47.02,
          },
          {
            name: 'Saturated Fat',
            amount: 5.87,
            unit: 'g',
            percentOfDailyNeeds: 38.51,
          },
          {
            name: 'Vitamin K',
            amount: 2.95,
            unit: 'µg',
            percentOfDailyNeeds: 6.26,
          },
          {
            name: 'Protein',
            amount: 46.98,
            unit: 'g',
            percentOfDailyNeeds: 95.11,
          },
          {
            name: 'Sugar',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 39.59,
          },
          {
            name: 'Caffeine',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin B3',
            amount: 8.93,
            unit: 'mg',
            percentOfDailyNeeds: 46.5,
          },
          {
            name: 'Vitamin C',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 0.54,
          },
          {
            name: 'Vitamin B12',
            amount: 5.51,
            unit: 'µg',
            percentOfDailyNeeds: 91.83,
          },
          {
            name: 'Vitamin B1',
            amount: 0.23,
            unit: 'mg',
            percentOfDailyNeeds: 16.18,
          },
          {
            name: 'Vitamin E',
            amount: 0.73,
            unit: 'mg',
            percentOfDailyNeeds: 12.18,
          },
          {
            name: 'Alcohol',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Iron',
            amount: 4.35,
            unit: 'mg',
            percentOfDailyNeeds: 27.6,
          },
          {
            name: 'Calories',
            amount: 351.46,
            unit: 'kcal',
            percentOfDailyNeeds: 27.44,
          },
          {
            name: 'Manganese',
            amount: 0.03,
            unit: 'mg',
            percentOfDailyNeeds: 6.24,
          },
          {
            name: 'Magnesium',
            amount: 52.15,
            unit: 'mg',
            percentOfDailyNeeds: 15.51,
          },
          {
            name: 'Sodium',
            amount: 179.13,
            unit: 'mg',
            percentOfDailyNeeds: 40.48,
          },
          {
            name: 'Vitamin B2',
            amount: 0.39,
            unit: 'mg',
            percentOfDailyNeeds: 24.62,
          },
        ],
      },
      {
        id: 1102047,
        name: 'salt and pepper',
        amount: 1,
        unit: 'servings',
        nutrients: [
          {
            name: 'Copper',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 11.7,
          },
          {
            name: 'Vitamin A',
            amount: 0,
            unit: 'IU',
            percentOfDailyNeeds: 4.13,
          },
          {
            name: 'Poly Unsaturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Folate',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 4.39,
          },
          {
            name: 'Folic Acid',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Cholesterol',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 46.86,
          },
          {
            name: 'Selenium',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 54.61,
          },
          {
            name: 'Choline',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Carbohydrates',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 13.62,
          },
          {
            name: 'Mono Unsaturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Potassium',
            amount: 0.04,
            unit: 'mg',
            percentOfDailyNeeds: 25.96,
          },
          {
            name: 'Calcium',
            amount: 0.12,
            unit: 'mg',
            percentOfDailyNeeds: 4.72,
          },
          {
            name: 'Fluoride',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Net Carbohydrates',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 14.63,
          },
          {
            name: 'Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 31.7,
          },
          {
            name: 'Vitamin B6',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 50.5,
          },
          {
            name: 'Vitamin B5',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 9.13,
          },
          {
            name: 'Zinc',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 66.01,
          },
          {
            name: 'Lycopene',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Fiber',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 2.49,
          },
          {
            name: 'Phosphorus',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 47.02,
          },
          {
            name: 'Saturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 38.51,
          },
          {
            name: 'Vitamin K',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 6.26,
          },
          {
            name: 'Vitamin B3',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 46.5,
          },
          {
            name: 'Protein',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 95.11,
          },
          {
            name: 'Sugar',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 39.59,
          },
          {
            name: 'Caffeine',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin D',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin C',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 0.54,
          },
          {
            name: 'Vitamin B12',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 91.83,
          },
          {
            name: 'Vitamin B1',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 16.18,
          },
          {
            name: 'Vitamin E',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 12.18,
          },
          {
            name: 'Alcohol',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin B2',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 24.62,
          },
          {
            name: 'Calories',
            amount: 0,
            unit: 'kcal',
            percentOfDailyNeeds: 27.44,
          },
          {
            name: 'Manganese',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 6.24,
          },
          {
            name: 'Magnesium',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 15.51,
          },
          {
            name: 'Sodium',
            amount: 193.79,
            unit: 'mg',
            percentOfDailyNeeds: 40.48,
          },
          {
            name: 'Iron',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 27.6,
          },
        ],
      },
      {
        id: 4582,
        name: 'oil',
        amount: 0.25,
        unit: 'Tbs',
        nutrients: [
          {
            name: 'Copper',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 11.7,
          },
          {
            name: 'Vitamin A',
            amount: 0,
            unit: 'IU',
            percentOfDailyNeeds: 4.13,
          },
          {
            name: 'Poly Unsaturated Fat',
            amount: 0.98,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Folate',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 4.39,
          },
          {
            name: 'Folic Acid',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Cholesterol',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 46.86,
          },
          {
            name: 'Selenium',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 54.61,
          },
          {
            name: 'Choline',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Carbohydrates',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 13.62,
          },
          {
            name: 'Mono Unsaturated Fat',
            amount: 2.22,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Potassium',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 25.96,
          },
          {
            name: 'Calcium',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 4.72,
          },
          {
            name: 'Net Carbohydrates',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 14.63,
          },
          {
            name: 'Fat',
            amount: 3.5,
            unit: 'g',
            percentOfDailyNeeds: 31.7,
          },
          {
            name: 'Vitamin B6',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 50.5,
          },
          {
            name: 'Vitamin B5',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 9.13,
          },
          {
            name: 'Zinc',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 66.01,
          },
          {
            name: 'Lycopene',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Fiber',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 2.49,
          },
          {
            name: 'Phosphorus',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 47.02,
          },
          {
            name: 'Saturated Fat',
            amount: 0.26,
            unit: 'g',
            percentOfDailyNeeds: 38.51,
          },
          {
            name: 'Vitamin K',
            amount: 2.5,
            unit: 'µg',
            percentOfDailyNeeds: 6.26,
          },
          {
            name: 'Vitamin B3',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 46.5,
          },
          {
            name: 'Protein',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 95.11,
          },
          {
            name: 'Sugar',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 39.59,
          },
          {
            name: 'Caffeine',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin D',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin C',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 0.54,
          },
          {
            name: 'Vitamin B12',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 91.83,
          },
          {
            name: 'Vitamin B1',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 16.18,
          },
          {
            name: 'Trans Fat',
            amount: 0.01,
            unit: 'g',
            percentOfDailyNeeds: 138.25,
          },
          {
            name: 'Vitamin E',
            amount: 0.61,
            unit: 'mg',
            percentOfDailyNeeds: 12.18,
          },
          {
            name: 'Alcohol',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Iron',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 27.6,
          },
          {
            name: 'Calories',
            amount: 30.94,
            unit: 'kcal',
            percentOfDailyNeeds: 27.44,
          },
          {
            name: 'Manganese',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 6.24,
          },
          {
            name: 'Magnesium',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 15.51,
          },
          {
            name: 'Sodium',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 40.48,
          },
          {
            name: 'Vitamin B2',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 24.62,
          },
        ],
      },
      {
        id: 2026,
        name: 'onion powder',
        amount: 0.13,
        unit: 'tsp',
        nutrients: [
          {
            name: 'Copper',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 11.7,
          },
          {
            name: 'Vitamin A',
            amount: 0,
            unit: 'IU',
            percentOfDailyNeeds: 4.13,
          },
          {
            name: 'Poly Unsaturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Folate',
            amount: 0.19,
            unit: 'µg',
            percentOfDailyNeeds: 4.39,
          },
          {
            name: 'Folic Acid',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Cholesterol',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 46.86,
          },
          {
            name: 'Selenium',
            amount: 0.04,
            unit: 'µg',
            percentOfDailyNeeds: 54.61,
          },
          {
            name: 'Choline',
            amount: 0.12,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Carbohydrates',
            amount: 0.24,
            unit: 'g',
            percentOfDailyNeeds: 13.62,
          },
          {
            name: 'Mono Unsaturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Potassium',
            amount: 2.95,
            unit: 'mg',
            percentOfDailyNeeds: 25.96,
          },
          {
            name: 'Calcium',
            amount: 1.15,
            unit: 'mg',
            percentOfDailyNeeds: 4.72,
          },
          {
            name: 'Net Carbohydrates',
            amount: 0.19,
            unit: 'g',
            percentOfDailyNeeds: 14.63,
          },
          {
            name: 'Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 31.7,
          },
          {
            name: 'Vitamin B6',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 50.5,
          },
          {
            name: 'Vitamin B5',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 9.13,
          },
          {
            name: 'Zinc',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 66.01,
          },
          {
            name: 'Lycopene',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Fiber',
            amount: 0.05,
            unit: 'g',
            percentOfDailyNeeds: 2.49,
          },
          {
            name: 'Phosphorus',
            amount: 0.97,
            unit: 'mg',
            percentOfDailyNeeds: 47.02,
          },
          {
            name: 'Saturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 38.51,
          },
          {
            name: 'Vitamin K',
            amount: 0.01,
            unit: 'µg',
            percentOfDailyNeeds: 6.26,
          },
          {
            name: 'Vitamin B3',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 46.5,
          },
          {
            name: 'Protein',
            amount: 0.03,
            unit: 'g',
            percentOfDailyNeeds: 95.11,
          },
          {
            name: 'Sugar',
            amount: 0.02,
            unit: 'g',
            percentOfDailyNeeds: 39.59,
          },
          {
            name: 'Caffeine',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin D',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin C',
            amount: 0.07,
            unit: 'mg',
            percentOfDailyNeeds: 0.54,
          },
          {
            name: 'Vitamin B12',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 91.83,
          },
          {
            name: 'Vitamin B1',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 16.18,
          },
          {
            name: 'Vitamin E',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 12.18,
          },
          {
            name: 'Alcohol',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Iron',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 27.6,
          },
          {
            name: 'Calories',
            amount: 1.02,
            unit: 'kcal',
            percentOfDailyNeeds: 27.44,
          },
          {
            name: 'Manganese',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 6.24,
          },
          {
            name: 'Magnesium',
            amount: 0.34,
            unit: 'mg',
            percentOfDailyNeeds: 15.51,
          },
          {
            name: 'Sodium',
            amount: 0.22,
            unit: 'mg',
            percentOfDailyNeeds: 40.48,
          },
          {
            name: 'Vitamin B2',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 24.62,
          },
        ],
      },
      {
        id: 1022020,
        name: 'garlic powder',
        amount: 0.06,
        unit: 'tsp',
        nutrients: [
          {
            name: 'Copper',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 11.7,
          },
          {
            name: 'Vitamin A',
            amount: 0,
            unit: 'IU',
            percentOfDailyNeeds: 4.13,
          },
          {
            name: 'Poly Unsaturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Folate',
            amount: 0.09,
            unit: 'µg',
            percentOfDailyNeeds: 4.39,
          },
          {
            name: 'Folic Acid',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Cholesterol',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 46.86,
          },
          {
            name: 'Selenium',
            amount: 0.05,
            unit: 'µg',
            percentOfDailyNeeds: 54.61,
          },
          {
            name: 'Choline',
            amount: 0.13,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Carbohydrates',
            amount: 0.14,
            unit: 'g',
            percentOfDailyNeeds: 13.62,
          },
          {
            name: 'Mono Unsaturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Potassium',
            amount: 2.31,
            unit: 'mg',
            percentOfDailyNeeds: 25.96,
          },
          {
            name: 'Calcium',
            amount: 0.15,
            unit: 'mg',
            percentOfDailyNeeds: 4.72,
          },
          {
            name: 'Net Carbohydrates',
            amount: 0.12,
            unit: 'g',
            percentOfDailyNeeds: 14.63,
          },
          {
            name: 'Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 31.7,
          },
          {
            name: 'Vitamin B6',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 50.5,
          },
          {
            name: 'Vitamin B5',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 9.13,
          },
          {
            name: 'Zinc',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 66.01,
          },
          {
            name: 'Lycopene',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Fiber',
            amount: 0.02,
            unit: 'g',
            percentOfDailyNeeds: 2.49,
          },
          {
            name: 'Phosphorus',
            amount: 0.8,
            unit: 'mg',
            percentOfDailyNeeds: 47.02,
          },
          {
            name: 'Saturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 38.51,
          },
          {
            name: 'Vitamin K',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 6.26,
          },
          {
            name: 'Vitamin B3',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 46.5,
          },
          {
            name: 'Protein',
            amount: 0.03,
            unit: 'g',
            percentOfDailyNeeds: 95.11,
          },
          {
            name: 'Sugar',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 39.59,
          },
          {
            name: 'Caffeine',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin D',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin C',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 0.54,
          },
          {
            name: 'Vitamin B12',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 91.83,
          },
          {
            name: 'Vitamin B1',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 16.18,
          },
          {
            name: 'Trans Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 138.25,
          },
          {
            name: 'Vitamin E',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 12.18,
          },
          {
            name: 'Alcohol',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Iron',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 27.6,
          },
          {
            name: 'Calories',
            amount: 0.64,
            unit: 'kcal',
            percentOfDailyNeeds: 27.44,
          },
          {
            name: 'Manganese',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 6.24,
          },
          {
            name: 'Magnesium',
            amount: 0.15,
            unit: 'mg',
            percentOfDailyNeeds: 15.51,
          },
          {
            name: 'Sodium',
            amount: 0.12,
            unit: 'mg',
            percentOfDailyNeeds: 40.48,
          },
          {
            name: 'Vitamin B2',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 24.62,
          },
        ],
      },
      {
        id: 1012028,
        name: 'paprika',
        amount: 0.06,
        unit: 'tsp',
        nutrients: [
          {
            name: 'Copper',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 11.7,
          },
          {
            name: 'Vitamin A',
            amount: 61.57,
            unit: 'IU',
            percentOfDailyNeeds: 4.13,
          },
          {
            name: 'Poly Unsaturated Fat',
            amount: 0.01,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Folate',
            amount: 0.06,
            unit: 'µg',
            percentOfDailyNeeds: 4.39,
          },
          {
            name: 'Folic Acid',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Cholesterol',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 46.86,
          },
          {
            name: 'Selenium',
            amount: 0.01,
            unit: 'µg',
            percentOfDailyNeeds: 54.61,
          },
          {
            name: 'Choline',
            amount: 0.06,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Carbohydrates',
            amount: 0.07,
            unit: 'g',
            percentOfDailyNeeds: 13.62,
          },
          {
            name: 'Mono Unsaturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Potassium',
            amount: 2.85,
            unit: 'mg',
            percentOfDailyNeeds: 25.96,
          },
          {
            name: 'Calcium',
            amount: 0.29,
            unit: 'mg',
            percentOfDailyNeeds: 4.72,
          },
          {
            name: 'Net Carbohydrates',
            amount: 0.02,
            unit: 'g',
            percentOfDailyNeeds: 14.63,
          },
          {
            name: 'Fat',
            amount: 0.02,
            unit: 'g',
            percentOfDailyNeeds: 31.7,
          },
          {
            name: 'Vitamin B6',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 50.5,
          },
          {
            name: 'Vitamin B5',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 9.13,
          },
          {
            name: 'Zinc',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 66.01,
          },
          {
            name: 'Lycopene',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Fiber',
            amount: 0.04,
            unit: 'g',
            percentOfDailyNeeds: 2.49,
          },
          {
            name: 'Phosphorus',
            amount: 0.39,
            unit: 'mg',
            percentOfDailyNeeds: 47.02,
          },
          {
            name: 'Saturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 38.51,
          },
          {
            name: 'Vitamin K',
            amount: 0.1,
            unit: 'µg',
            percentOfDailyNeeds: 6.26,
          },
          {
            name: 'Vitamin B3',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 46.5,
          },
          {
            name: 'Protein',
            amount: 0.02,
            unit: 'g',
            percentOfDailyNeeds: 95.11,
          },
          {
            name: 'Sugar',
            amount: 0.01,
            unit: 'g',
            percentOfDailyNeeds: 39.59,
          },
          {
            name: 'Caffeine',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin D',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin C',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 0.54,
          },
          {
            name: 'Vitamin B12',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 91.83,
          },
          {
            name: 'Vitamin B1',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 16.18,
          },
          {
            name: 'Trans Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 138.25,
          },
          {
            name: 'Vitamin E',
            amount: 0.04,
            unit: 'mg',
            percentOfDailyNeeds: 12.18,
          },
          {
            name: 'Alcohol',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Iron',
            amount: 0.03,
            unit: 'mg',
            percentOfDailyNeeds: 27.6,
          },
          {
            name: 'Calories',
            amount: 0.35,
            unit: 'kcal',
            percentOfDailyNeeds: 27.44,
          },
          {
            name: 'Manganese',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 6.24,
          },
          {
            name: 'Magnesium',
            amount: 0.22,
            unit: 'mg',
            percentOfDailyNeeds: 15.51,
          },
          {
            name: 'Sodium',
            amount: 0.09,
            unit: 'mg',
            percentOfDailyNeeds: 40.48,
          },
          {
            name: 'Vitamin B2',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 24.62,
          },
        ],
      },
      {
        id: 1002014,
        name: 'cumin',
        amount: 0.06,
        unit: 'tsp',
        nutrients: [
          {
            name: 'Copper',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 11.7,
          },
          {
            name: 'Vitamin A',
            amount: 1.59,
            unit: 'IU',
            percentOfDailyNeeds: 4.13,
          },
          {
            name: 'Poly Unsaturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Folate',
            amount: 0.01,
            unit: 'µg',
            percentOfDailyNeeds: 4.39,
          },
          {
            name: 'Folic Acid',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Cholesterol',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 46.86,
          },
          {
            name: 'Selenium',
            amount: 0.01,
            unit: 'µg',
            percentOfDailyNeeds: 54.61,
          },
          {
            name: 'Choline',
            amount: 0.03,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Carbohydrates',
            amount: 0.06,
            unit: 'g',
            percentOfDailyNeeds: 13.62,
          },
          {
            name: 'Mono Unsaturated Fat',
            amount: 0.02,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Potassium',
            amount: 2.23,
            unit: 'mg',
            percentOfDailyNeeds: 25.96,
          },
          {
            name: 'Calcium',
            amount: 1.16,
            unit: 'mg',
            percentOfDailyNeeds: 4.72,
          },
          {
            name: 'Fat',
            amount: 0.03,
            unit: 'g',
            percentOfDailyNeeds: 31.7,
          },
          {
            name: 'Net Carbohydrates',
            amount: 0.04,
            unit: 'g',
            percentOfDailyNeeds: 14.63,
          },
          {
            name: 'Vitamin B6',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 50.5,
          },
          {
            name: 'Zinc',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 66.01,
          },
          {
            name: 'Lycopene',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Fiber',
            amount: 0.01,
            unit: 'g',
            percentOfDailyNeeds: 2.49,
          },
          {
            name: 'Phosphorus',
            amount: 0.62,
            unit: 'mg',
            percentOfDailyNeeds: 47.02,
          },
          {
            name: 'Saturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 38.51,
          },
          {
            name: 'Vitamin K',
            amount: 0.01,
            unit: 'µg',
            percentOfDailyNeeds: 6.26,
          },
          {
            name: 'Vitamin B3',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 46.5,
          },
          {
            name: 'Protein',
            amount: 0.02,
            unit: 'g',
            percentOfDailyNeeds: 95.11,
          },
          {
            name: 'Sugar',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 39.59,
          },
          {
            name: 'Caffeine',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin D',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin C',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 0.54,
          },
          {
            name: 'Vitamin B12',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 91.83,
          },
          {
            name: 'Vitamin B1',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 16.18,
          },
          {
            name: 'Vitamin E',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 12.18,
          },
          {
            name: 'Alcohol',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Iron',
            amount: 0.08,
            unit: 'mg',
            percentOfDailyNeeds: 27.6,
          },
          {
            name: 'Calories',
            amount: 0.47,
            unit: 'kcal',
            percentOfDailyNeeds: 27.44,
          },
          {
            name: 'Manganese',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 6.24,
          },
          {
            name: 'Magnesium',
            amount: 0.46,
            unit: 'mg',
            percentOfDailyNeeds: 15.51,
          },
          {
            name: 'Sodium',
            amount: 0.21,
            unit: 'mg',
            percentOfDailyNeeds: 40.48,
          },
          {
            name: 'Vitamin B2',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 24.62,
          },
        ],
      },
      {
        id: 2031,
        name: 'cayenne pepper',
        amount: 0.03,
        unit: 'tsp',
        nutrients: [
          {
            name: 'Copper',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 11.7,
          },
          {
            name: 'Vitamin A',
            amount: 23.41,
            unit: 'IU',
            percentOfDailyNeeds: 4.13,
          },
          {
            name: 'Poly Unsaturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Folate',
            amount: 0.06,
            unit: 'µg',
            percentOfDailyNeeds: 4.39,
          },
          {
            name: 'Folic Acid',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Cholesterol',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 46.86,
          },
          {
            name: 'Selenium',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 54.61,
          },
          {
            name: 'Choline',
            amount: 0.03,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Carbohydrates',
            amount: 0.03,
            unit: 'g',
            percentOfDailyNeeds: 13.62,
          },
          {
            name: 'Mono Unsaturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Potassium',
            amount: 1.13,
            unit: 'mg',
            percentOfDailyNeeds: 25.96,
          },
          {
            name: 'Calcium',
            amount: 0.08,
            unit: 'mg',
            percentOfDailyNeeds: 4.72,
          },
          {
            name: 'Fat',
            amount: 0.01,
            unit: 'g',
            percentOfDailyNeeds: 31.7,
          },
          {
            name: 'Net Carbohydrates',
            amount: 0.02,
            unit: 'g',
            percentOfDailyNeeds: 14.63,
          },
          {
            name: 'Vitamin B6',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 50.5,
          },
          {
            name: 'Zinc',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 66.01,
          },
          {
            name: 'Lycopene',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Fiber',
            amount: 0.02,
            unit: 'g',
            percentOfDailyNeeds: 2.49,
          },
          {
            name: 'Phosphorus',
            amount: 0.16,
            unit: 'mg',
            percentOfDailyNeeds: 47.02,
          },
          {
            name: 'Saturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 38.51,
          },
          {
            name: 'Vitamin K',
            amount: 0.05,
            unit: 'µg',
            percentOfDailyNeeds: 6.26,
          },
          {
            name: 'Vitamin B3',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 46.5,
          },
          {
            name: 'Protein',
            amount: 0.01,
            unit: 'g',
            percentOfDailyNeeds: 95.11,
          },
          {
            name: 'Sugar',
            amount: 0.01,
            unit: 'g',
            percentOfDailyNeeds: 39.59,
          },
          {
            name: 'Caffeine',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin D',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin C',
            amount: 0.04,
            unit: 'mg',
            percentOfDailyNeeds: 0.54,
          },
          {
            name: 'Vitamin B12',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 91.83,
          },
          {
            name: 'Vitamin B1',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 16.18,
          },
          {
            name: 'Vitamin E',
            amount: 0.02,
            unit: 'mg',
            percentOfDailyNeeds: 12.18,
          },
          {
            name: 'Alcohol',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Iron',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 27.6,
          },
          {
            name: 'Calories',
            amount: 0.18,
            unit: 'kcal',
            percentOfDailyNeeds: 27.44,
          },
          {
            name: 'Manganese',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 6.24,
          },
          {
            name: 'Magnesium',
            amount: 0.09,
            unit: 'mg',
            percentOfDailyNeeds: 15.51,
          },
          {
            name: 'Sodium',
            amount: 0.02,
            unit: 'mg',
            percentOfDailyNeeds: 40.48,
          },
          {
            name: 'Vitamin B2',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 24.62,
          },
        ],
      },
      {
        id: 6150,
        name: 'smokey barbecue sauce',
        amount: 0.19,
        unit: 'cups',
        nutrients: [
          {
            name: 'Copper',
            amount: 0.04,
            unit: 'mg',
            percentOfDailyNeeds: 11.7,
          },
          {
            name: 'Vitamin A',
            amount: 120.12,
            unit: 'IU',
            percentOfDailyNeeds: 4.13,
          },
          {
            name: 'Poly Unsaturated Fat',
            amount: 0.05,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Folate',
            amount: 1.07,
            unit: 'µg',
            percentOfDailyNeeds: 4.39,
          },
          {
            name: 'Folic Acid',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Cholesterol',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 46.86,
          },
          {
            name: 'Selenium',
            amount: 0.7,
            unit: 'µg',
            percentOfDailyNeeds: 54.61,
          },
          {
            name: 'Choline',
            amount: 3.81,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Carbohydrates',
            amount: 21.88,
            unit: 'g',
            percentOfDailyNeeds: 13.62,
          },
          {
            name: 'Mono Unsaturated Fat',
            amount: 0.04,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Potassium',
            amount: 124.41,
            unit: 'mg',
            percentOfDailyNeeds: 25.96,
          },
          {
            name: 'Calcium',
            amount: 17.7,
            unit: 'mg',
            percentOfDailyNeeds: 4.72,
          },
          {
            name: 'Net Carbohydrates',
            amount: 21.4,
            unit: 'g',
            percentOfDailyNeeds: 14.63,
          },
          {
            name: 'Fat',
            amount: 0.34,
            unit: 'g',
            percentOfDailyNeeds: 31.7,
          },
          {
            name: 'Vitamin B6',
            amount: 0.04,
            unit: 'mg',
            percentOfDailyNeeds: 50.5,
          },
          {
            name: 'Vitamin B5',
            amount: 0.09,
            unit: 'mg',
            percentOfDailyNeeds: 9.13,
          },
          {
            name: 'Zinc',
            amount: 0.09,
            unit: 'mg',
            percentOfDailyNeeds: 66.01,
          },
          {
            name: 'Lycopene',
            amount: 2439.94,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Fiber',
            amount: 0.48,
            unit: 'g',
            percentOfDailyNeeds: 2.49,
          },
          {
            name: 'Phosphorus',
            amount: 10.73,
            unit: 'mg',
            percentOfDailyNeeds: 47.02,
          },
          {
            name: 'Saturated Fat',
            amount: 0.02,
            unit: 'g',
            percentOfDailyNeeds: 38.51,
          },
          {
            name: 'Vitamin K',
            amount: 0.97,
            unit: 'µg',
            percentOfDailyNeeds: 6.26,
          },
          {
            name: 'Vitamin B3',
            amount: 0.32,
            unit: 'mg',
            percentOfDailyNeeds: 46.5,
          },
          {
            name: 'Protein',
            amount: 0.44,
            unit: 'g',
            percentOfDailyNeeds: 95.11,
          },
          {
            name: 'Sugar',
            amount: 17.8,
            unit: 'g',
            percentOfDailyNeeds: 39.59,
          },
          {
            name: 'Caffeine',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin D',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin C',
            amount: 0.32,
            unit: 'mg',
            percentOfDailyNeeds: 0.54,
          },
          {
            name: 'Vitamin B12',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 91.83,
          },
          {
            name: 'Vitamin B1',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 16.18,
          },
          {
            name: 'Trans Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 138.25,
          },
          {
            name: 'Vitamin E',
            amount: 0.43,
            unit: 'mg',
            percentOfDailyNeeds: 12.18,
          },
          {
            name: 'Alcohol',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Iron',
            amount: 0.34,
            unit: 'mg',
            percentOfDailyNeeds: 27.6,
          },
          {
            name: 'Calories',
            amount: 92.24,
            unit: 'kcal',
            percentOfDailyNeeds: 27.44,
          },
          {
            name: 'Manganese',
            amount: 0.07,
            unit: 'mg',
            percentOfDailyNeeds: 6.24,
          },
          {
            name: 'Magnesium',
            amount: 6.97,
            unit: 'mg',
            percentOfDailyNeeds: 15.51,
          },
          {
            name: 'Sodium',
            amount: 552.34,
            unit: 'mg',
            percentOfDailyNeeds: 40.48,
          },
          {
            name: 'Vitamin B2',
            amount: 0.03,
            unit: 'mg',
            percentOfDailyNeeds: 24.62,
          },
        ],
      },
      {
        id: 19334,
        name: 'brown sugar',
        amount: 0.04,
        unit: 'cup',
        nutrients: [
          {
            name: 'Copper',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 11.7,
          },
          {
            name: 'Vitamin A',
            amount: 0,
            unit: 'IU',
            percentOfDailyNeeds: 4.13,
          },
          {
            name: 'Poly Unsaturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Folate',
            amount: 0.09,
            unit: 'µg',
            percentOfDailyNeeds: 4.39,
          },
          {
            name: 'Folic Acid',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Cholesterol',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 46.86,
          },
          {
            name: 'Selenium',
            amount: 0.11,
            unit: 'µg',
            percentOfDailyNeeds: 54.61,
          },
          {
            name: 'Choline',
            amount: 0.21,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Carbohydrates',
            amount: 8.99,
            unit: 'g',
            percentOfDailyNeeds: 13.62,
          },
          {
            name: 'Mono Unsaturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Potassium',
            amount: 12.19,
            unit: 'mg',
            percentOfDailyNeeds: 25.96,
          },
          {
            name: 'Calcium',
            amount: 7.61,
            unit: 'mg',
            percentOfDailyNeeds: 4.72,
          },
          {
            name: 'Net Carbohydrates',
            amount: 8.99,
            unit: 'g',
            percentOfDailyNeeds: 14.63,
          },
          {
            name: 'Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 31.7,
          },
          {
            name: 'Vitamin B6',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 50.5,
          },
          {
            name: 'Vitamin B5',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 9.13,
          },
          {
            name: 'Zinc',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 66.01,
          },
          {
            name: 'Lycopene',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Fiber',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 2.49,
          },
          {
            name: 'Phosphorus',
            amount: 0.37,
            unit: 'mg',
            percentOfDailyNeeds: 47.02,
          },
          {
            name: 'Saturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 38.51,
          },
          {
            name: 'Vitamin K',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 6.26,
          },
          {
            name: 'Vitamin B3',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 46.5,
          },
          {
            name: 'Protein',
            amount: 0.01,
            unit: 'g',
            percentOfDailyNeeds: 95.11,
          },
          {
            name: 'Sugar',
            amount: 8.89,
            unit: 'g',
            percentOfDailyNeeds: 39.59,
          },
          {
            name: 'Caffeine',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin D',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin C',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 0.54,
          },
          {
            name: 'Vitamin B12',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 91.83,
          },
          {
            name: 'Vitamin B1',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 16.18,
          },
          {
            name: 'Vitamin E',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 12.18,
          },
          {
            name: 'Alcohol',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Iron',
            amount: 0.07,
            unit: 'mg',
            percentOfDailyNeeds: 27.6,
          },
          {
            name: 'Calories',
            amount: 34.83,
            unit: 'kcal',
            percentOfDailyNeeds: 27.44,
          },
          {
            name: 'Manganese',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 6.24,
          },
          {
            name: 'Magnesium',
            amount: 0.83,
            unit: 'mg',
            percentOfDailyNeeds: 15.51,
          },
          {
            name: 'Sodium',
            amount: 2.57,
            unit: 'mg',
            percentOfDailyNeeds: 40.48,
          },
          {
            name: 'Vitamin B2',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 24.62,
          },
        ],
      },
      {
        id: 19334,
        name: 'brown sugar',
        amount: 0.04,
        unit: 'cup',
        nutrients: [
          {
            name: 'Copper',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 11.7,
          },
          {
            name: 'Vitamin A',
            amount: 0,
            unit: 'IU',
            percentOfDailyNeeds: 4.13,
          },
          {
            name: 'Poly Unsaturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Folate',
            amount: 0.09,
            unit: 'µg',
            percentOfDailyNeeds: 4.39,
          },
          {
            name: 'Folic Acid',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Cholesterol',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 46.86,
          },
          {
            name: 'Selenium',
            amount: 0.11,
            unit: 'µg',
            percentOfDailyNeeds: 54.61,
          },
          {
            name: 'Choline',
            amount: 0.21,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Carbohydrates',
            amount: 8.99,
            unit: 'g',
            percentOfDailyNeeds: 13.62,
          },
          {
            name: 'Mono Unsaturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Potassium',
            amount: 12.19,
            unit: 'mg',
            percentOfDailyNeeds: 25.96,
          },
          {
            name: 'Calcium',
            amount: 7.61,
            unit: 'mg',
            percentOfDailyNeeds: 4.72,
          },
          {
            name: 'Net Carbohydrates',
            amount: 8.99,
            unit: 'g',
            percentOfDailyNeeds: 14.63,
          },
          {
            name: 'Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 31.7,
          },
          {
            name: 'Vitamin B6',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 50.5,
          },
          {
            name: 'Vitamin B5',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 9.13,
          },
          {
            name: 'Zinc',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 66.01,
          },
          {
            name: 'Lycopene',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Fiber',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 2.49,
          },
          {
            name: 'Phosphorus',
            amount: 0.37,
            unit: 'mg',
            percentOfDailyNeeds: 47.02,
          },
          {
            name: 'Saturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 38.51,
          },
          {
            name: 'Vitamin K',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 6.26,
          },
          {
            name: 'Vitamin B3',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 46.5,
          },
          {
            name: 'Protein',
            amount: 0.01,
            unit: 'g',
            percentOfDailyNeeds: 95.11,
          },
          {
            name: 'Sugar',
            amount: 8.89,
            unit: 'g',
            percentOfDailyNeeds: 39.59,
          },
          {
            name: 'Caffeine',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin D',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin C',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 0.54,
          },
          {
            name: 'Vitamin B12',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 91.83,
          },
          {
            name: 'Vitamin B1',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 16.18,
          },
          {
            name: 'Vitamin E',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 12.18,
          },
          {
            name: 'Alcohol',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Iron',
            amount: 0.07,
            unit: 'mg',
            percentOfDailyNeeds: 27.6,
          },
          {
            name: 'Calories',
            amount: 34.83,
            unit: 'kcal',
            percentOfDailyNeeds: 27.44,
          },
          {
            name: 'Manganese',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 6.24,
          },
          {
            name: 'Magnesium',
            amount: 0.83,
            unit: 'mg',
            percentOfDailyNeeds: 15.51,
          },
          {
            name: 'Sodium',
            amount: 2.57,
            unit: 'mg',
            percentOfDailyNeeds: 40.48,
          },
          {
            name: 'Vitamin B2',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 24.62,
          },
        ],
      },
      {
        id: 20027,
        name: 'cornstarch',
        amount: 0.06,
        unit: 'tbsp',
        nutrients: [
          {
            name: 'Copper',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 11.7,
          },
          {
            name: 'Vitamin A',
            amount: 0,
            unit: 'IU',
            percentOfDailyNeeds: 4.13,
          },
          {
            name: 'Poly Unsaturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Folate',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 4.39,
          },
          {
            name: 'Folic Acid',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Cholesterol',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 46.86,
          },
          {
            name: 'Selenium',
            amount: 0.01,
            unit: 'µg',
            percentOfDailyNeeds: 54.61,
          },
          {
            name: 'Choline',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Carbohydrates',
            amount: 0.46,
            unit: 'g',
            percentOfDailyNeeds: 13.62,
          },
          {
            name: 'Mono Unsaturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Potassium',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 25.96,
          },
          {
            name: 'Calcium',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 4.72,
          },
          {
            name: 'Net Carbohydrates',
            amount: 0.45,
            unit: 'g',
            percentOfDailyNeeds: 14.63,
          },
          {
            name: 'Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 31.7,
          },
          {
            name: 'Vitamin B6',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 50.5,
          },
          {
            name: 'Vitamin B5',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 9.13,
          },
          {
            name: 'Zinc',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 66.01,
          },
          {
            name: 'Lycopene',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Fiber',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 2.49,
          },
          {
            name: 'Phosphorus',
            amount: 0.06,
            unit: 'mg',
            percentOfDailyNeeds: 47.02,
          },
          {
            name: 'Saturated Fat',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 38.51,
          },
          {
            name: 'Vitamin K',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 6.26,
          },
          {
            name: 'Vitamin B3',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 46.5,
          },
          {
            name: 'Protein',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 95.11,
          },
          {
            name: 'Sugar',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 39.59,
          },
          {
            name: 'Caffeine',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin D',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Vitamin C',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 0.54,
          },
          {
            name: 'Vitamin B12',
            amount: 0,
            unit: 'µg',
            percentOfDailyNeeds: 91.83,
          },
          {
            name: 'Vitamin B1',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 16.18,
          },
          {
            name: 'Vitamin E',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 12.18,
          },
          {
            name: 'Alcohol',
            amount: 0,
            unit: 'g',
            percentOfDailyNeeds: 0,
          },
          {
            name: 'Iron',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 27.6,
          },
          {
            name: 'Calories',
            amount: 1.9,
            unit: 'kcal',
            percentOfDailyNeeds: 27.44,
          },
          {
            name: 'Manganese',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 6.24,
          },
          {
            name: 'Magnesium',
            amount: 0.01,
            unit: 'mg',
            percentOfDailyNeeds: 15.51,
          },
          {
            name: 'Sodium',
            amount: 0.05,
            unit: 'mg',
            percentOfDailyNeeds: 40.48,
          },
          {
            name: 'Vitamin B2',
            amount: 0,
            unit: 'mg',
            percentOfDailyNeeds: 24.62,
          },
        ],
      },
    ],
    caloricBreakdown: {
      percentProtein: 35.28,
      percentFat: 34.4,
      percentCarbs: 30.32,
    },
    weightPerServing: {
      amount: 304,
      unit: 'g',
    },
  },
  taste: {
    sweetness: 47.64,
    saltiness: 100,
    sourness: 28.04,
    bitterness: 16.82,
    savoriness: 59.01,
    fattiness: 51.5,
    spiciness: 18000,
  },
  summary:
    'BBQ Beef Brisket is a Jewish main course. For <b>$3.07 per serving</b>, this recipe <b>covers 25%</b> of your daily requirements of vitamins and minerals. This recipe serves 8. Watching your figure? This gluten free and dairy free recipe has <b>514 calories</b>, <b>48g of protein</b>, and <b>21g of fat</b> per serving. 19 people have made this recipe and would make it again. From preparation to the plate, this recipe takes around <b>45 minutes</b>. A mixture of onion powder, smokey barbecue sauce, oil, and a handful of other ingredients are all it takes to make this recipe so yummy. It is perfect for <b>Hanukkah</b>. It is brought to you by Foodista. Taking all factors into account, this recipe <b>earns a spoonacular score of 69%</b>, which is pretty good. If you like this recipe, you might also like recipes such as <a href="https://spoonacular.com/recipes/bbq-beef-brisket-128731">BBQ Beef Brisket</a>, <a href="https://spoonacular.com/recipes/bbq-beef-brisket-597496">BBQ Beef Brisket</a>, and <a href="https://spoonacular.com/recipes/bbq-beef-brisket-1371705">BBQ Beef Brisket</a>.',
  cuisines: ['Jewish'],
  dishTypes: ['lunch', 'main course', 'main dish', 'dinner'],
  diets: ['gluten free', 'dairy free'],
  occasions: ['hanukkah'],
  winePairing: {
    pairedWines: ['shiraz', 'tempranillo', 'zinfandel'],
    pairingText:
      "Shiraz, Tempranillo, and Zinfandel are great choices for Brisket. All these red wines can handle the meaty, smokey flavor of brisket. If you're talking traditional Jewish brisket, you'll want to look for a kosher red wine. The PlumpJack Syrah with a 4.4 out of 5 star rating seems like a good match. It costs about 63 dollars per bottle.",
    productMatches: [
      {
        id: 433696,
        title: 'PlumpJack Syrah',
        description:
          '#53 Wine Spectator Top 100 of 2017 The Syrah grapes are sourced from two amazing vineyards in the Napa Valley – Hudson in Los Carneros and Stagecoach on Atlas Peak. These unique AVAs lend this wine its signature characteristics. The cool, foggy Hudson vineyard imparts this wine with a smoky, gamey nose layered with white and black pepper along with some floral notes, while the sunny and rocky Stagecoach vineyard lends this wine intense and concentrated fruit aromas of blackberry, boysenberry, and huckleberry pie. The Hudson vineyard also brings beautiful, bright raspberries, black pepper, smoke, finesse, and a lively acid to the palate, whereas the\nStagecoach vineyard adds dark fruit, great concentration, and structure. The whole-cluster fermentation adds more complexity with some green peppercorn and spice in the finish, and the oak imparts smokiness to the nose and bittersweet chocolate to the finish.',
        price: '$62.99',
        imageUrl: 'https://img.spoonacular.com/products/433696-312x231.jpg',
        averageRating: 0.8799999952316284,
        ratingCount: 5,
        score: 0.8175,
        link: 'https://click.linksynergy.com/deeplink?id=*QCiIS6t4gA&mid=2025&murl=https%3A%2F%2Fwww.wine.com%2Fproduct%2Fplumpjack-syrah-2014%2F160264',
      },
    ],
  },
  instructions:
    'Trim any large, thick pieces of fat from the brisket (dont remove all of the fat because it keeps the meat moist during cooking and adds flavor)\nSprinkle brisket with salt and pepper.\nMix the onion powder, garlic powder, smoked paprika, cumin, and cayenne pepper together in a small bowl.\nDry rub both sides of the brisket with the seasoning mixture.\nHeat oil in a pan over medium-high heat and sear the meat on both sides.\nRemove from the heat and set aside.\nStir together the honey barbecue sauce and brown sugar.\nPour half of the sauce into the bottom of your slow cooker.\nPlace the brisket, fatty side up, into the slow cooker.\nCover the top o the brisket with the remaining sauce.\nCover the slow cooker and set heat to low for 9 hours, or until fork tender.\nWhen the brisket is cooked, remove it carefully from the slow cooker and place it on a cutting board.\nPour the sauce from the slow cooker into a saucepan and let it cool.\nSkim the fat that has risen to the top of the sauce in the large bowl.\nIt will appear lighter in color than the sauce, like droplets of oil on the surface. Skim as much fat as you can.\nIn a small bowl, stir together cornstarch and 1 tbs. of water till completely smooth.\nPour the cornstarch mixture into the bowl of sauce and stir to combine.\nReduce the sauce quickly in a saucepan on the stovetop by simmering it to 10 minutes.\nPour the sauce over the brisket and serve.\nThe leftovers make great BBQ sandwiches.\nIf you like crockpot food, be sure to check out some of my favorite recipes at www.mealdiva.com',
  analyzedInstructions: [
    {
      name: '',
      steps: [
        {
          number: 1,
          step: 'Trim any large, thick pieces of fat from the brisket (dont remove all of the fat because it keeps the meat moist during cooking and adds flavor)',
          ingredients: [
            {
              id: 1065062,
              name: 'meat',
              localizedName: 'meat',
              image:
                'https://spoonacular.com/cdn/ingredients_100x100/whole-chicken.jpg',
            },
          ],
          equipment: [],
        },
        {
          number: 2,
          step: 'Sprinkle brisket with salt and pepper.',
          ingredients: [
            {
              id: 1102047,
              name: 'salt and pepper',
              localizedName: 'salt and pepper',
              image:
                'https://spoonacular.com/cdn/ingredients_100x100/salt-and-pepper.jpg',
            },
          ],
          equipment: [],
        },
        {
          number: 3,
          step: 'Mix the onion powder, garlic powder, smoked paprika, cumin, and cayenne pepper together in a small bowl.',
          ingredients: [
            {
              id: 2031,
              name: 'cayenne pepper',
              localizedName: 'cayenne pepper',
              image:
                'https://spoonacular.com/cdn/ingredients_100x100/chili-powder.jpg',
            },
            {
              id: 1012028,
              name: 'smoked paprika',
              localizedName: 'smoked paprika',
              image:
                'https://spoonacular.com/cdn/ingredients_100x100/paprika.jpg',
            },
            {
              id: 1022020,
              name: 'garlic powder',
              localizedName: 'garlic powder',
              image:
                'https://spoonacular.com/cdn/ingredients_100x100/garlic-powder.png',
            },
            {
              id: 2026,
              name: 'onion powder',
              localizedName: 'onion powder',
              image:
                'https://spoonacular.com/cdn/ingredients_100x100/onion-powder.jpg',
            },
            {
              id: 1002014,
              name: 'cumin',
              localizedName: 'cumin',
              image:
                'https://spoonacular.com/cdn/ingredients_100x100/ground-cumin.jpg',
            },
          ],
          equipment: [
            {
              id: 404783,
              name: 'bowl',
              localizedName: 'bowl',
              image: 'https://spoonacular.com/cdn/equipment_100x100/bowl.jpg',
            },
          ],
        },
        {
          number: 4,
          step: 'Dry rub both sides of the brisket with the seasoning mixture.',
          ingredients: [
            {
              id: 1042027,
              name: 'seasoning',
              localizedName: 'seasoning',
              image:
                'https://spoonacular.com/cdn/ingredients_100x100/seasoning.png',
            },
            {
              id: 1012034,
              name: 'dry seasoning rub',
              localizedName: 'dry seasoning rub',
              image:
                'https://spoonacular.com/cdn/ingredients_100x100/seasoning.png',
            },
          ],
          equipment: [],
        },
        {
          number: 5,
          step: 'Heat oil in a pan over medium-high heat and sear the meat on both sides.',
          ingredients: [
            {
              id: 1065062,
              name: 'meat',
              localizedName: 'meat',
              image:
                'https://spoonacular.com/cdn/ingredients_100x100/whole-chicken.jpg',
            },
            {
              id: 4582,
              name: 'cooking oil',
              localizedName: 'cooking oil',
              image:
                'https://spoonacular.com/cdn/ingredients_100x100/vegetable-oil.jpg',
            },
          ],
          equipment: [
            {
              id: 404645,
              name: 'frying pan',
              localizedName: 'frying pan',
              image: 'https://spoonacular.com/cdn/equipment_100x100/pan.png',
            },
          ],
        },
        {
          number: 6,
          step: 'Remove from the heat and set aside.',
          ingredients: [],
          equipment: [],
        },
        {
          number: 7,
          step: 'Stir together the honey barbecue sauce and brown sugar.',
          ingredients: [
            {
              id: 6150,
              name: 'barbecue sauce',
              localizedName: 'barbecue sauce',
              image:
                'https://spoonacular.com/cdn/ingredients_100x100/barbecue-sauce.jpg',
            },
            {
              id: 19334,
              name: 'brown sugar',
              localizedName: 'brown sugar',
              image:
                'https://spoonacular.com/cdn/ingredients_100x100/dark-brown-sugar.png',
            },
            {
              id: 19296,
              name: 'honey',
              localizedName: 'honey',
              image:
                'https://spoonacular.com/cdn/ingredients_100x100/honey.png',
            },
          ],
          equipment: [],
        },
        {
          number: 8,
          step: 'Pour half of the sauce into the bottom of your slow cooker.',
          ingredients: [
            {
              id: 0,
              name: 'sauce',
              localizedName: 'sauce',
              image: '',
            },
          ],
          equipment: [
            {
              id: 404718,
              name: 'slow cooker',
              localizedName: 'slow cooker',
              image:
                'https://spoonacular.com/cdn/equipment_100x100/slow-cooker.jpg',
            },
          ],
        },
        {
          number: 9,
          step: 'Place the brisket, fatty side up, into the slow cooker.',
          ingredients: [],
          equipment: [
            {
              id: 404718,
              name: 'slow cooker',
              localizedName: 'slow cooker',
              image:
                'https://spoonacular.com/cdn/equipment_100x100/slow-cooker.jpg',
            },
          ],
        },
        {
          number: 10,
          step: 'Cover the top o the brisket with the remaining sauce.',
          ingredients: [
            {
              id: 0,
              name: 'sauce',
              localizedName: 'sauce',
              image: '',
            },
          ],
          equipment: [],
        },
        {
          number: 11,
          step: 'Cover the slow cooker and set heat to low for 9 hours, or until fork tender.',
          ingredients: [],
          equipment: [
            {
              id: 404718,
              name: 'slow cooker',
              localizedName: 'slow cooker',
              image:
                'https://spoonacular.com/cdn/equipment_100x100/slow-cooker.jpg',
            },
          ],
          length: {
            number: 540,
            unit: 'minutes',
          },
        },
        {
          number: 12,
          step: 'When the brisket is cooked, remove it carefully from the slow cooker and place it on a cutting board.',
          ingredients: [],
          equipment: [
            {
              id: 404716,
              name: 'cutting board',
              localizedName: 'cutting board',
              image:
                'https://spoonacular.com/cdn/equipment_100x100/cutting-board.jpg',
            },
            {
              id: 404718,
              name: 'slow cooker',
              localizedName: 'slow cooker',
              image:
                'https://spoonacular.com/cdn/equipment_100x100/slow-cooker.jpg',
            },
          ],
        },
        {
          number: 13,
          step: 'Pour the sauce from the slow cooker into a saucepan and let it cool.',
          ingredients: [
            {
              id: 0,
              name: 'sauce',
              localizedName: 'sauce',
              image: '',
            },
          ],
          equipment: [
            {
              id: 404718,
              name: 'slow cooker',
              localizedName: 'slow cooker',
              image:
                'https://spoonacular.com/cdn/equipment_100x100/slow-cooker.jpg',
            },
            {
              id: 404669,
              name: 'sauce pan',
              localizedName: 'sauce pan',
              image:
                'https://spoonacular.com/cdn/equipment_100x100/sauce-pan.jpg',
            },
          ],
        },
        {
          number: 14,
          step: 'Skim the fat that has risen to the top of the sauce in the large bowl.',
          ingredients: [
            {
              id: 0,
              name: 'sauce',
              localizedName: 'sauce',
              image: '',
            },
          ],
          equipment: [
            {
              id: 404783,
              name: 'bowl',
              localizedName: 'bowl',
              image: 'https://spoonacular.com/cdn/equipment_100x100/bowl.jpg',
            },
          ],
        },
        {
          number: 15,
          step: 'It will appear lighter in color than the sauce, like droplets of oil on the surface. Skim as much fat as you can.',
          ingredients: [
            {
              id: 0,
              name: 'sauce',
              localizedName: 'sauce',
              image: '',
            },
            {
              id: 4582,
              name: 'cooking oil',
              localizedName: 'cooking oil',
              image:
                'https://spoonacular.com/cdn/ingredients_100x100/vegetable-oil.jpg',
            },
          ],
          equipment: [],
        },
        {
          number: 16,
          step: 'In a small bowl, stir together cornstarch and 1 tbs. of water till completely smooth.',
          ingredients: [
            {
              id: 20027,
              name: 'corn starch',
              localizedName: 'corn starch',
              image:
                'https://spoonacular.com/cdn/ingredients_100x100/white-powder.jpg',
            },
            {
              id: 14412,
              name: 'water',
              localizedName: 'water',
              image:
                'https://spoonacular.com/cdn/ingredients_100x100/water.png',
            },
          ],
          equipment: [
            {
              id: 404783,
              name: 'bowl',
              localizedName: 'bowl',
              image: 'https://spoonacular.com/cdn/equipment_100x100/bowl.jpg',
            },
          ],
        },
        {
          number: 17,
          step: 'Pour the cornstarch mixture into the bowl of sauce and stir to combine.',
          ingredients: [
            {
              id: 20027,
              name: 'corn starch',
              localizedName: 'corn starch',
              image:
                'https://spoonacular.com/cdn/ingredients_100x100/white-powder.jpg',
            },
            {
              id: 0,
              name: 'sauce',
              localizedName: 'sauce',
              image: '',
            },
          ],
          equipment: [
            {
              id: 404783,
              name: 'bowl',
              localizedName: 'bowl',
              image: 'https://spoonacular.com/cdn/equipment_100x100/bowl.jpg',
            },
          ],
        },
        {
          number: 18,
          step: 'Reduce the sauce quickly in a saucepan on the stovetop by simmering it to 10 minutes.',
          ingredients: [
            {
              id: 0,
              name: 'sauce',
              localizedName: 'sauce',
              image: '',
            },
          ],
          equipment: [
            {
              id: 404669,
              name: 'sauce pan',
              localizedName: 'sauce pan',
              image:
                'https://spoonacular.com/cdn/equipment_100x100/sauce-pan.jpg',
            },
            {
              id: 404794,
              name: 'stove',
              localizedName: 'stove',
              image: 'https://spoonacular.com/cdn/equipment_100x100/oven.jpg',
            },
          ],
          length: {
            number: 10,
            unit: 'minutes',
          },
        },
        {
          number: 19,
          step: 'Pour the sauce over the brisket and serve.',
          ingredients: [
            {
              id: 0,
              name: 'sauce',
              localizedName: 'sauce',
              image: '',
            },
          ],
          equipment: [],
        },
        {
          number: 20,
          step: 'The leftovers make great BBQ sandwiches.',
          ingredients: [],
          equipment: [],
        },
        {
          number: 21,
          step: 'If you like crockpot food, be sure to check out some of my favorite recipes at www.mealdiva.com',
          ingredients: [],
          equipment: [
            {
              id: 404718,
              name: 'slow cooker',
              localizedName: 'slow cooker',
              image:
                'https://spoonacular.com/cdn/equipment_100x100/slow-cooker.jpg',
            },
          ],
        },
      ],
    },
  ],
  originalId: null,
  spoonacularScore: 74.59261322021484,
  spoonacularSourceUrl: 'https://spoonacular.com/bbq-beef-brisket-634486',
};
