# Generated by Django 4.2.11 on 2024-04-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auth_id", models.CharField(max_length=255, unique=True)),
                ("auth_provider", models.CharField(max_length=50)),
            ],
        ),
    ]
