# Generated by Django 5.0.4 on 2024-04-19 07:00

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", authentication.models.CustomUserManager()),
            ],
        ),
    ]
