# Generated by Django 5.0.4 on 2024-04-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_dietarypreferences_dietarypreference_and_more"),
        ("authentication", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="dietary_preferences",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="api.dietarypreference"
            ),
        ),
    ]
