name: Expo Doctor

on:
  push:
    branches-ignore:
      - main
    paths:
      - "package.json"
      - "pnpm-lock.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "package.json"
      - "pnpm-lock.yaml"

jobs:
  expo-doctor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Expo Doctor Checks
        run: npx expo-doctor@latest